# Copyright (c) 2018 CA. All rights reserved.
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.

version: '3.4'
services:
  gateway-dev:
    hostname: localhost
    image: caapim/gateway:latest
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8000:8000"
    volumes:
      - /opt/SecureSpan/Gateway/node/default/etc/bootstrap/services/restman
      - ./deployment/build/gateway/deployment-0.6.0.gw7:/opt/docker/rc.d/deployment.gw7
    secrets:
      - source: license
        target: /opt/SecureSpan/Gateway/node/default/etc/bootstrap/license/license.xml
    environment:
      ACCEPT_LICENSE: "true"
      SSG_ADMIN_USERNAME: "admin"
      SSG_ADMIN_PASSWORD: "password"
      EXTRA_JAVA_ARGS: "-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n"
      ENV.PROPERTY.gateway.template: "docker env variable"
      ENV.CONTEXT_VARIABLE_PROPERTY.env-configuration.example: "example value"
      ENV.PASSWORD.password: "super secret"
      ENV.CONTEXT_VARIABLE_PROPERTY.influxdb.influxdb: "influxdb"
      ENV.CONTEXT_VARIABLE_PROPERTY.influxdb.tags: "env=design"
secrets:
  license:
    file: ./docker/license.xml